config/routes.rb
Rails.application.routes.draw do

  root 'items#index'

  get 'sessions/new'

  get '/login',   to: 'sessions#new'

  post '/login',   to: 'sessions#create'

  delete '/logout',  to: 'sessions#destroy'

  post '/tags',   to: 'tags#create'

  get '/cart',   to: 'cart_items#index'

  resources :tags do
    member do
      get :relative_items
    end
  end

  resources :items

  resources :users do
    member do
      get :add_cart_items
      post :add_cart_items
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :item
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :item_id, presence: true
  validates :cart_item_number, presence: true, numericality: { greater_than: 0 }
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :tag_relationships, foreign_key: "relative_item_id",
                                dependent:  :destroy
  has_many :relative_tags, through: :tag_relationships
  has_many :cart_items, dependent: :destroy
  has_many :add_cart_users, through: :cart_items, source: :user
  validates :name,  presence: true, uniqueness: { case_sensitive: false }
  validates :picture, presence: true
  validates :per_cost, presence: true, numericality: { greater_than: 99 }
  validates :description, presence: true
  validates :stock_number, presence: true, numericality: { greater_than: 0 }


  def follow(tag)
    relative_tags << tag
  end

  def unfollow(tag)
    tag_relationships.find_by(relative_tag_id: tag.id).destroy
  end

  def following?(tag)
    relative_tags.include?(tag)
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  # has_many :order_items dependent: :destroy
  default_scope -> { order(ordered_at: :desc) }
  validates :user_id, presence: true
  validates :shipped_user_name,  presence: true
  validates :shipped_postal_code,  presence: true
  validates :shipped_address,  presence: true
  validates :shipped_phone_number,  presence: true
  validates :billing_amount,  presence: true, numericality: { only_integer: true }
  validates :ordered_digest,  presence: true, uniqueness: { case_sensitive: false }
  validates :ordered_at,  presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_relationships, foreign_key: "relative_tag_id",
                                dependent:  :destroy
  has_many :relative_items, through: :tag_relationships
  validates :name,  presence: true, uniqueness: { case_sensitive: false },
            length: { minimum: 1 }

  def followed_by?(item)
    relative_items.include?(item)
  end

end

app/models/tag_relationship.rb
class TagRelationship < ApplicationRecord
  belongs_to :relative_item, class_name: "Item"
  belongs_to :relative_tag, class_name: "Tag"
  validates :relative_item_id, presence: true
  validates :relative_tag_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :add_cart_items, through: :cart_items, source: :item
  has_many :orders
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  validates :postal_code, presence: true, numericality: { only_integer: true },
                          length: { is: 7 }
  validates :address, presence: true, length: { minimum: 8 }
  validates :phone_number, presence: true, numericality: { only_integer: true },
                          length: { minimum: 9 }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def add_cart_item(item, cart_item_number)
    cart_items.create!(cart_item_number: cart_item_number, user_id: self.id, item_id: item.id)
  end

  def destroy_cart_item(item)
    cart_items.find_by(item_id: item.id).destroy!
  end

  def add_cart_item?(item)
    add_cart_items.include?(item)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def show
    @item = Item.find(params[:id])
    @relative_tags = @item.relative_tags
  end

  def index
    @items = Item.all
    @items = Item.order('updated_at DESC').paginate(page: params[:page], per_page: 12)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path
    else
      flash.now[:danger] = '正しいメールもしくはパスワードではありません。'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def create
  end

  def relative_items
    @tag = Tag.find(params[:id])
    @relative_items = @tag.relative_items.paginate(page: params[:page], per_page: 12)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def add_cart_items
    @user = User.find(params[:id])
    @item = Item.find(params[:id])
    @cart_items = @user.cart_items
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(item, size: 350)
    gravatar_id = Digest::MD5::hexdigest(item.name.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: item.name, class: "gravatar")
  end

end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart_items/index.html.erb
<h1>CartItems#index</h1>
<p>Find me in app/views/cart_items/index.html.erb</p>

app/views/cart_items/show.html.erb
<a href="<%= add_cart_items_user_path(@user) %>">

app/views/items/index.html.erb
<% provide(:title, "ホーム") %>

<h1 class='heading'>
  商品一覧
</h1>

<div class="list-items">
  <% @items.each do |item| %>
    <ul class="list-item">
      <li class="list-item__image"><%= image_tag '商品-64.jpg' %></li>
      <li class="list-item__name"><%= link_to item.name, item %></li>
      <li class="list-item__per_cost">価格: <%= item.per_cost %>円</li>
      <li class="list-item__stock_number">在庫数：<%= item.stock_number %></li>
      <li class="list-item__tags">
        <% item.relative_tags.each do |relative_tag| %>
            <div class="list-item__tag">
                <%= link_to relative_tag.name, relative_items_tag_path(relative_tag) %>
            </div>
        <% end %>
      </li>
    </ul>
  <% end %>
</div>


<div class="paging">
  <%= will_paginate %>
</div>

app/views/items/show.html.erb
<% provide(:title, @item.name) %>

<section class="item-info-main">
    <div class="item-image"><%= image_tag '商品-64.jpg' %></div>
    <div class="item-about">
        <div class="item-about__name"><%= @item.name %></div>
        <div class="item-about__price">価格   ¥<%= @item.per_cost %></div>
        <div class="item-about__send-cost">配送料一律 ¥300</div>
        <div class="item-about__stock-number">在庫数: <%= @item.stock_number %></div>
        <div class="item-about__purchase-number">
            <div class="item-about__purchase-number__text">数量: </div>
            <select name="数量">
                <% @item.stock_number.times do |n| %>
                    <option value="#{n + 1}"><%= n + 1 %></option>
                <% end %>
            </select>
        </div>
        <input class="item-about__add-cart" type="button" value="カートに入れる">
        <div class="item-about__tags">
          <% @relative_tags.each do |tag| %>
              <div class="item-about__tag">
                  <%= link_to tag.name, relative_items_tag_path(tag) %>
              </div>
          <% end %>
        </div>
    </div>
</section>

<section class="item-info-more">
    <div class="item-info-more__heading">商品詳細</div>
    <div class="item-info-more__description"> <%= @item.description %></div>
</section>

app/views/tags/relative_items.html.erb
<% provide(:title, @tag.name) %>

<h1 class='heading'>
  <%= @tag.name %>の関連商品
</h1>

<div class="list-items">
  <% @relative_items.each do |item| %>
    <ul class="list-item">
      <li class="list-item__image"><%= image_tag '商品-64.jpg' %></li>
      <li class="list-item__name"><%= link_to item.name, item %></li>
      <li class="list-item__per_cost">価格: <%= item.per_cost %>円</li>
      <li class="list-item__stock_number">在庫数：<%= item.stock_number %></li>
      <li class="list-item__tags">
        <% item.relative_tags.each do |relative_tag| %>
            <div class="list-item__tag">
                <%= link_to relative_tag.name, relative_items_tag_path(relative_tag) %>
            </div>
        <% end %>
      </li>
    </ul>
  <% end %>
</div>

<div class="paging">
  <%= will_paginate @relative_items %>
</div>

app/views/tags/show.html.erb
<% provide(:title, @tag.name) %>

<h1 class='heading'>
  <%= @tag.name %>の関連商品
</h1>

<div class="list-items">
  <% @relative_items.each do |item| %>
    <ul class="list-item">
      <li class="list-item__image"><%= image_tag '商品-64.jpg' %></li>
      <li class="list-item__name"><%= link_to item.name, item %><li>
      <li class="list-item__per_cost">価格: <%= item.per_cost %>円<li>
      <li class="list-item__stock_number">在庫数：<%= item.stock_number %><li>
    </ul>
  <% end %>
</div>

app/views/users/add_cart_items.html.erb
<% provide(:title, "カート商品") %>

<h1 class='cart-heading'>
  ショッピングカート
</h1>

<section class="cart-items">
  <div class="cart-items__heading">
    <div class="cart-items__heading-list-1">商品</div>
    <div class="cart-items__heading-list-2">価格</div>
    <div class="cart-items__heading-list-3">数量</div>
  </div>
  <div class="cart-items__list">
    <% @user.add_cart_items.each do |add_cart_item| %>
      <div class="cart-items__item">
        <div class="cart-items__item-picture"><%= image_tag '商品-64.jpg' %></div>
        <div class="cart-items__item-info">
          <div class="cart-items__item-name"><%= link_to add_cart_item.name, add_cart_item %></div>
          <div class="cart-items__item-stock-number">在庫数：<%= add_cart_item.stock_number %></div>
          <div class="cart-items__item-tags">
            <% add_cart_item.relative_tags.each do |relative_tag| %>
                <div class="list-item__tag">
                    <%= link_to relative_tag.name, relative_items_tag_path(relative_tag) %>
                </div>
            <% end %>
          </div>
          <div class="cart-items__item-delete-button">
            <input type="button" value="削除">
          </div>
        </div>
        <div class="cart-items__item-price"><%= add_cart_item.per_cost %>円</div>
        <div class="cart-items__item-number">
          <select name="数量">
            <% add_cart_item.stock_number.times do |n| %>
                <option value="#{n + 1}"><%= n + 1 %></option>
            <% end %>
          </select>
        </div>
      </div>
    <% end %>
  </div>
</section>

<section class="order">
  <h3 class="order__total-fee">合計<%= @user.cart_items.count %>点：円</h3>
  <input class="item-about__add-cart" type="button" value="注文を確定する">
</section>

<section class="shipping">
  <div class="shipping-heading">お届け先情報</div>
  <div class="shipping-info"><%= @user.name %>  様</div>
  <div class="shipping-info">郵便番号： <%= @user.postal_code %></div>
  <div class="shipping-info">お届け住所： <%= @user.address %></div>
</section>

<section class="shipping">
  <div class="shipping-heading">お支払い方法</div>
  <div class="shipping-info">代金引換のみご利用いただけます。手数料は一律150円です。</div>
</section>

app/views/users/new.html.erb
<!-- 無くて良い機能 -->
<% provide(:title, 'ユーザー登録') %>
<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name, 'ユーザー名* （ フルネームでご記入下さい ）' %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, 'メールアドレス* （ 半角英数字でご記入下さい ）' %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, 'パスワード* （ 6文字以上の半角英数字でご記入下さい ）' %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, 'パスワードの再入力*' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :postal_code, '郵便番号* （ 記入例: 1111111 ）' %>
      <%= f.password_field :postal_code, class: 'form-control' %>

      <%= f.label :address, '住所* （ 記入例: 東京都品川区3-1-1 品川ビル103号 ）' %>
      <%= f.password_field :address, class: 'form-control' %>

      <%= f.label :phone_number, '電話番号* （ 記入例: 034567847 ）' %>
      <%= f.password_field :phone_number, class: 'form-control' %>

      <%= f.submit "アカウントを作成する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>